/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SchoolManage__factory } from "./SchoolManage__factory";
export { Web3BridgeGarage__factory } from "./Web3BridgeGarage__factory";
