/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SchoolManage {
  export type StudentStruct = {
    studentOwner: AddressLike;
    name: string;
    age: BigNumberish;
    email: string;
    homeAddress: string;
    id: BigNumberish;
    status: BigNumberish;
  };

  export type StudentStructOutput = [
    studentOwner: string,
    name: string,
    age: bigint,
    email: string,
    homeAddress: string,
    id: bigint,
    status: bigint
  ] & {
    studentOwner: string;
    name: string;
    age: bigint;
    email: string;
    homeAddress: string;
    id: bigint;
    status: bigint;
  };
}

export interface SchoolManageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateStudent"
      | "counter"
      | "createStudent"
      | "deferStudent"
      | "deleteStudent"
      | "getStudent"
      | "getStudentStatus"
      | "getStudents"
      | "owner"
      | "rusticateStudent"
      | "students"
      | "updateStudent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activateStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "counter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createStudent",
    values: [string, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deferStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudents",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rusticateStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStudent",
    values: [BigNumberish, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "counter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deferStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStudent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStudentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rusticateStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStudent",
    data: BytesLike
  ): Result;
}

export interface SchoolManage extends BaseContract {
  connect(runner?: ContractRunner | null): SchoolManage;
  waitForDeployment(): Promise<this>;

  interface: SchoolManageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateStudent: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  counter: TypedContractMethod<[], [bigint], "view">;

  createStudent: TypedContractMethod<
    [_name: string, _age: BigNumberish, _email: string, _homeAddress: string],
    [void],
    "nonpayable"
  >;

  deferStudent: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  deleteStudent: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  getStudent: TypedContractMethod<
    [_index: BigNumberish],
    [SchoolManage.StudentStructOutput],
    "view"
  >;

  getStudentStatus: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getStudents: TypedContractMethod<
    [],
    [SchoolManage.StudentStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  rusticateStudent: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  students: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, bigint] & {
        studentOwner: string;
        name: string;
        age: bigint;
        email: string;
        homeAddress: string;
        id: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  updateStudent: TypedContractMethod<
    [
      _index: BigNumberish,
      _name: string,
      _age: BigNumberish,
      _homeAddress: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateStudent"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "counter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createStudent"
  ): TypedContractMethod<
    [_name: string, _age: BigNumberish, _email: string, _homeAddress: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deferStudent"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteStudent"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getStudent"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [SchoolManage.StudentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudentStatus"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getStudents"
  ): TypedContractMethod<[], [SchoolManage.StudentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rusticateStudent"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, string, bigint, bigint] & {
        studentOwner: string;
        name: string;
        age: bigint;
        email: string;
        homeAddress: string;
        id: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateStudent"
  ): TypedContractMethod<
    [
      _index: BigNumberish,
      _name: string,
      _age: BigNumberish,
      _homeAddress: string
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
