/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SchoolManage } from "./SchoolManage";
export type { Web3BridgeGarage } from "./Web3BridgeGarage";
export * as factories from "./factories";
export { SchoolManage__factory } from "./factories/SchoolManage__factory";
export { Web3BridgeGarage__factory } from "./factories/Web3BridgeGarage__factory";
